#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys

import pisi
from buildfarm import utils

if __name__ == "__main__":
    stable_packages = {}
    new_packages = []

    testing_dir = utils.get_compiled_packages_directory()
    stable_dir = utils.get_stable_packages_directory()

    if not stable_dir:
        print "You don't have a stable repository on this buildfarm."
        sys.exit(1)

    testing_index = pisi.index.Index(os.path.join(testing_dir, "pisi-index.xml"))
    stable_index = pisi.index.Index(os.path.join(stable_dir, "pisi-index.xml"))

    for package in stable_index.packages:
        stable_packages[package.name] = package

    for package in testing_index.packages:
        if os.path.exists(os.path.join(stable_dir, package.packageURI)):
            continue

        status = "A"
        update_action = " "

        old_stable = stable_packages.get(package.name)
        if old_stable:
            status = "U"
            if package.has_update_type("security", old_stable.history[0].release):
                update_action = "S"
            elif package.has_update_type("critical", old_stable.history[0].release):
                update_action = "C"

        new_packages.append((package.source.name, package.packageURI, status, update_action))

    new_packages.sort()

    old_source = new_packages[0][0]
    for source, filename, status, update_action in new_packages:
        if source != old_source:
            print
            old_source = source
        print "%s%s %s" % (status, update_action, filename)
